name: Build and Push Docker image

on:
  push:
    tags:
      - v*.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Setting up the build function of Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Build and push the Docker Image
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/inlaze-frontend-challenge:latest
            ${{ secrets.DOCKER_USERNAME }}/inlaze-frontend-challenge:${{ github.ref_name }}